---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faster
  name: oteldb
  labels:
    app: oteldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oteldb
  template:
    metadata:
      labels:
        app: oteldb
        service.opentelemetry.io/name: go-faster.oteldb
    spec:
      containers:
        - name: oteldb
          image: ghcr.io/go-faster/oteldb:main
          livenessProbe:
            tcpSocket:
              port: 4317
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 3200
              protocol: TCP
              name: tempo-http
            - containerPort: 9090
              protocol: TCP
              name: prom-http
            - containerPort: 3100
              protocol: TCP
              name: loki-http
            - containerPort: 4317
              protocol: TCP
              name: otlp-grpc
            - containerPort: 4318
              protocol: TCP
              name: otlp-http
          resources:
            requests:
              cpu: "3"
              memory: 512Mi
            limits:
              cpu: "6"
              memory: 4Gi
          env:
            - name: GOMEMLIMIT
              value: "4GiB"
            - name: GOMAXPROCS
              value: "6"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=go-faster.oteldb"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTELDB_STORAGE
              value: ch
            - name: CH_DSN
              valueFrom:
                secretKeyRef:
                  name: oteldb
                  key: CH_DSN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faster
  name: otelproxy
  labels:
    app: otelproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelproxy
  template:
    metadata:
      labels:
        app: otelproxy
        service.opentelemetry.io/name: go-faster.otelproxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
    spec:
      containers:
        - name: oteldb
          image: ghcr.io/go-faster/oteldb/proxy:main
          ports:
            - containerPort: 8090
              protocol: TCP
              name: metrics
            - containerPort: 9090
              protocol: TCP
              name: prometheus
            - containerPort: 3100
              protocol: TCP
              name: loki
            - containerPort: 3200
              protocol: TCP
              name: tempo
          resources:
            requests:
              cpu: 500m
              memory: 128M
            limits:
              cpu: 1500m
              memory: 256M
          env:
            - name: PROMETHEUS_URL
              value: http://vmselect-cluster.monitoring.svc.cluster.local:8481/select/0/prometheus/
            - name: LOKI_URL
              value: http://loki-gateway.monitoring.svc.cluster.local
            - name: TEMPO_URL
              value: http://tempo-gateway.monitoring.svc.cluster.local
            - name: GOMEMLIMIT
              value: "256MiB"
            - name: GOMAXPROCS
              value: "2"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "8090"
            - name: OTEL_EXPORTER_PROMETHEUS_HOST
              value: "0.0.0.0"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=go-faster.otelproxy"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faster
  name: otelfaker
  labels:
    app: otelfaker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: otelfaker
  template:
    metadata:
      labels:
        app: otelfaker
        service.opentelemetry.io/name: go-faster.otelfaker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
    spec:
      containers:
        - name: oteldb
          image: ghcr.io/go-faster/oteldb/faker:main
          ports:
            - containerPort: 8090
              protocol: TCP
              name: metrics
          resources:
            requests:
              cpu: 500m
              memory: 128M
            limits:
              cpu: 1500m
              memory: 256M
          env:
            - name: GOMEMLIMIT
              value: "256MiB"
            - name: GOMAXPROCS
              value: "2"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "8090"
            - name: OTEL_EXPORTER_PROMETHEUS_HOST
              value: "0.0.0.0"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=go-faster.otelfaker"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faster
  name: chotel
  labels:
    app: chotel
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chotel
  template:
    metadata:
      labels:
        app: chotel
        service.opentelemetry.io/name: go-faster.chotel
    spec:
      containers:
        - name: oteldb
          image: ghcr.io/go-faster/oteldb/chotel:main
          resources:
            requests:
              cpu: 500m
              memory: 128M
            limits:
              cpu: 1500m
              memory: 256M
          env:
            - name: GOMEMLIMIT
              value: "256MiB"
            - name: GOMAXPROCS
              value: "2"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=go-faster.chotel"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: CH_DSN
              valueFrom:
                secretKeyRef:
                  name: oteldb
                  key: CH_DSN