---
apiVersion: v1
kind: Service
metadata:
  namespace: faster
  name: oteldb
  labels:
    app: oteldb
    prometheus: "true"
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
      name: metrics
    - port: 3200
      protocol: TCP
      targetPort: 3200
      name: tempo-http
    - port: 4317
      protocol: TCP
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      protocol: TCP
      targetPort: 4318
      name: otlp-http
  selector:
    app: oteldb
  sessionAffinity: None
