global:
  scrape_interval: 1s

scrape_configs:
  # For PromQL compliance tester
  # https://github.com/prometheus/compliance/tree/main/promql#promql-compliance-tester
  - job_name: 'demo'
    scrape_interval: 1s
    static_configs:
      - targets:
          - 'demo-1:8080'
          - 'demo-2:8080'
          - 'demo-3:8080'
  - job_name: otel-collector
    scrape_interval: 5s
    static_configs:
      - targets: [otelcol:8888]
  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: [node-exporter:9100]
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [prometheus:9090]
  - job_name: clickhouse
    scrape_interval: 5s
    static_configs:
      - targets: [clickhouse:8080]
  - job_name: faker
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'faker-api:9464'
remote_write:
  - url: http://oteldb:19291
