apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelbot.fullname" . }}
  labels:
    {{- include "otelbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 13133
      protocol: TCP
      targetPort: 13133
      name: health-check
  selector:
    {{- include "otelbot.selectorLabels" . | nindent 4 }}
