apiVersion: 1

datasources:
  - name: "TraceQL"
    type: tempo
    access: proxy
    orgId: 1
    url: http://oteldb:3200
    uid: tempo-oteldb
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: 'loki-oteldb'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: service.name
            value: service_name
      tracesToMetrics:
        datasourceUid: 'prom-oteldb'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags:
          - key: service.name
            value: service_name
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prom-oteldb
      lokiSearch:
        datasourceUid: 'loki-oteldb'

  - name: "LogQL"
    type: loki
    access: proxy
    orgId: 1
    url: http://oteldb:3100
    uid: loki-oteldb
    jsonData:
      serviceMap:
        datasourceUid: prom-oteldb
      maxLines: 500
      derivedFields:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: tempo-oteldb
          matcherRegex: '"trace_id":"([0-9a-f]+)"'
          name: trace
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
          # optional for URL Label to set a custom display label for the link.
          urlDisplayLabel: 'View Trace'

  - name: "PromQL"
    type: prometheus
    access: proxy
    orgId: 1
    isDefault: true
    url: http://oteldb:9090
    uid: prom-oteldb

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      port: 9000
      server: clickhouse
      tlsSkipVerify: true
