apiVersion: 1

datasources:
  - name: "TraceQL"
    type: tempo
    access: proxy
    orgId: 1
    url: http://oteldb:3200
    uid: tempo-oteldb
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prom-oteldb

  - name: "LogQL"
    type: loki
    access: proxy
    orgId: 1
    url: http://oteldb:3100
    uid: loki-oteldb
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  - name: "PromQL"
    type: prometheus
    access: proxy
    orgId: 1
    isDefault: true
    url: http://oteldb:9090
    uid: prom-oteldb

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      port: 9000
      server: clickhouse
      tlsSkipVerify: true
