ignore:
  - "**/main.go"
  - "**/*_enum.go"
  - "*_enum.go"
  - "**/*_gen.go"
  # Skip non-production code.
  - "internal/lokiproxy/"
  - "internal/pyroproxy/"
  # Skip vendored-forked
  - "internal/promcompliance/"
coverage:
  status:
    project: false
    patch: false
