ignore:
  - "**/main.go"
  - "**/*_enum.go"
  - "*_enum.go"
  - "**/*_gen.go"
  # Skip non-production code.
  - "internal/lokiproxy/"
  - "internal/pyroproxy/"
  - "internal/promproxy/"
  - "internal/otelbench/"
  - "cmd/oteldemo/"
  - "cmd/otelproxy/"
  # Skip vendored-forked
  - "internal/promcompliance/"
  # Skip benchmarks
  - "cmd/otelbench/"
  # Skip complience tests
  - "cmd/promql-compliance-tester/"
coverage:
  status:
    project: false
    patch: false
