version: "2"
linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 120
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
        - whyNoLint
        - singleCaseSwitch
        - commentedOutCode
        - appendAssign
        - unnecessaryBlock
        - redundantSprint
        - octalLiteral
        - typeDefFirst
        - unnamedResult
        - ptrToRefParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115 # Annoying and have a lot of false-positive results.
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
    staticcheck:
      checks:
        - "*"
        - "-QF1001" # Suggested simplification via De Morgan's law is not always better.
        - "-QF1008" # Too much false positives, embedding is fine.
  exclusions:
    generated: lax
    rules:
      # Disable linters that are annoying in tests.
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter

      # Allow unused context.Context
      - linters:
          - revive
        text: unused-parameter
        source: .+\s+context.Context

      - linters:
          - gocritic
        path: _test\.go
        text: Combine

      # Check that equal to self is true
      - linters:
          - gocritic
        path: _test\.go
        text: dupArg
        source: (assert|require).+Equal

      # Ignore shadowing of err.
      - linters:
          - govet
        text: declaration of "(err|ctx|log|lg|c)"

      # Probably some broken linter for generics?
      - linters:
          - revive
        text: 'receiver-naming: receiver name \S+ should be consistent with previous receiver name \S+ for invalid-type'

      # Ignore linters in main packages.
      - linters:
          - funlen
          - gocognit
          - goconst
          - gocyclo
        path: main\.go

      - linters:
          - staticcheck
        text: ST1003 # underscores lol
        source: func Fuzz.+\(f \*testing\.F\)

      # Do not need comments in internal/binary packages.
      - linters:
          - revive
          - staticcheck
        path: (internal|cmd)
        text: comment

      # Ignore linters in third-party code.
      - linters:
          - revive
        path: internal/promcompliance
        text: "exported:"
      - linters:
          - gocritic
        path: internal/promcompliance
        text: "ifElseChain:"

      - linters:
          - revive
        text: comment on exported const .+ should be of the form
      - linters:
          - revive
        text: exported const .+ should have comment

      # It's okay for commands to write files and exec binaries.
      - linters:
          - gosec
        path: cmd
        text: G(307|306|301|204)

      # False positive.
      - linters:
          - govet
        text: method Seek
        source: func.+Seek\(.+int64\).+chunkenc\.ValueType

      # Not gonna use const, does not make any sense.
      - linters:
          - goconst
        text: (Int64|int)
      - linters:
          - goconst
        path: internal/logparser
        text: (trace|span)_?[Ii][Dd]

      - linters:
          - staticcheck
        path: internal/prompb

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/go-faster/oteldb
  exclusions:
    generated: lax
