version: "2"
linters:
  default: standard
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - hugeParam # We don't care about huge parameters much. Too many false positives.
        - rangeValCopy # We don't care about range copies much. Too many false positives.
        - unnecessaryBlock # Sometimes we need to use blocks for readability.
        - ptrToRefParam # Too many false positives.
        - exitAfterDefer # Too many false positives.
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G115 # Annoying and have a lot of false-positive results.
    lll:
      line-length: 140
    misspell:
      locale: US
    staticcheck:
      checks:
        - "*"
        - "-QF1001" # Suggested simplification via De Morgan's law is not always better.
        - "-QF1008" # Too much false positives, embedding is fine.
  exclusions:
    generated: lax
    rules:
      # Disable linters that are annoying in tests.
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter

      # Allow unused context.Context
      - linters:
          - revive
        text: unused-parameter
        source: .+\s+context.Context

      # Do not need comments in internal/binary packages.
      - linters:
          - revive
          - staticcheck
        path: (internal|cmd)
        text: comment

      # Ignore some linters in third-party code.
      - linters:
          - gocritic
        path: internal/promcompliance
        text: "ifElseChain:"
      - linters:
          - unused
        path: internal/otelreceiver/prometheusremotewrite
      - linters:
          - staticcheck
        path: internal/prompb

      # It's okay for commands to write files and exec binaries.
      - linters:
          - gosec
        path: cmd
        text: G(307|306|301|204)

      # False positive.
      - linters:
          - govet
        text: method Seek
        source: func.+Seek\(.+int64\).+chunkenc\.ValueType

      # Not gonna use const, does not make any sense.
      - linters:
          - goconst
        path: internal/logparser
        text: (trace|span)_?[Ii][Dd]

      # Our AST packages contain a lot of interface-based sum types.
      # Defining methods in one place next to the interface is better for readability.
      - linters:
          - gocritic
        path: internal/(logql|traceql)/[^/]+\.go$
        text: "typeDefFirst:"
formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/go-faster/oteldb
  exclusions:
    generated: lax
