// Code generated by ogen, DO NOT EDIT.

package pyroscopeapi

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// IngestParams is parameters of ingest operation.
type IngestParams struct {
	Name SegmentKey
	// Start of time range in `attime` format.
	// Defaults to now.
	From OptAtTime
	// End of time range in `attime` format.
	// Defaults to now.
	Until OptAtTime
	// Sample rate.
	// Defaults to `100`.
	// NOTE: Pyroscope ignores parameter if it is invalid.
	SampleRate OptUint32
	SpyName    OptString
	// Could be
	// - `samples`
	// - `objects`
	// - `goroutines`
	// - `bytes`
	// - `lock_nanoseconds`
	// - `lock_samples`
	// but Pyroscope does not check it, so we don't either.
	Units OptString
	// Could be
	// - `average`
	// - `sum`
	// but Pyroscope does not check it, so we don't either.
	AggregationType OptString
	// Input format.
	Format OptString
}

func unpackIngestParams(packed middleware.Parameters) (params IngestParams) {
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		params.Name = packed[key].(SegmentKey)
	}
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.From = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "until",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Until = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sampleRate",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SampleRate = v.(OptUint32)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "spyName",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SpyName = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "units",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Units = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "aggregationType",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.AggregationType = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "format",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Format = v.(OptString)
		}
	}
	return params
}

func decodeIngestParams(args [0]string, argsEscaped bool, r *http.Request) (params IngestParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Name = SegmentKey(paramsDotNameVal)
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFromVal AtTime
				if err := func() error {
					var paramsDotFromValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotFromValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotFromVal = AtTime(paramsDotFromValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.From.SetTo(paramsDotFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: until.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "until",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUntilVal AtTime
				if err := func() error {
					var paramsDotUntilValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotUntilValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotUntilVal = AtTime(paramsDotUntilValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.Until.SetTo(paramsDotUntilVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "until",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: sampleRate.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sampleRate",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSampleRateVal uint32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUint32(val)
					if err != nil {
						return err
					}

					paramsDotSampleRateVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SampleRate.SetTo(paramsDotSampleRateVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sampleRate",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: spyName.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "spyName",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSpyNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSpyNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SpyName.SetTo(paramsDotSpyNameVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "spyName",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: units.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "units",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUnitsVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotUnitsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Units.SetTo(paramsDotUnitsVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "units",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: aggregationType.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "aggregationType",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAggregationTypeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAggregationTypeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AggregationType.SetTo(paramsDotAggregationTypeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "aggregationType",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: format.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "format",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFormatVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotFormatVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Format.SetTo(paramsDotFormatVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "format",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// LabelValuesParams is parameters of labelValues operation.
type LabelValuesParams struct {
	// Label to lookup values.
	Label string
	// Start of time range in `attime` format.
	// For now, Pyroscope ignores parameter, if `query` is not set.
	From OptAtTime
	// End of time range in `attime` format.
	// For now, Pyroscope ignores parameter, if `query` is not set.
	Until OptAtTime
	// FrameQL query.
	Query OptString
}

func unpackLabelValuesParams(packed middleware.Parameters) (params LabelValuesParams) {
	{
		key := middleware.ParameterKey{
			Name: "label",
			In:   "query",
		}
		params.Label = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.From = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "until",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Until = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "query",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Query = v.(OptString)
		}
	}
	return params
}

func decodeLabelValuesParams(args [0]string, argsEscaped bool, r *http.Request) (params LabelValuesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: label.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "label",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Label = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "label",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFromVal AtTime
				if err := func() error {
					var paramsDotFromValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotFromValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotFromVal = AtTime(paramsDotFromValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.From.SetTo(paramsDotFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: until.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "until",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUntilVal AtTime
				if err := func() error {
					var paramsDotUntilValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotUntilValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotUntilVal = AtTime(paramsDotUntilValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.Until.SetTo(paramsDotUntilVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "until",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: query.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "query",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQueryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQueryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Query.SetTo(paramsDotQueryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "query",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// LabelsParams is parameters of labels operation.
type LabelsParams struct {
	// Start of time range in `attime` format.
	// For now, Pyroscope ignores parameter, if `query` is not set.
	From OptAtTime
	// End of time range in `attime` format.
	// For now, Pyroscope ignores parameter, if `query` is not set.
	Until OptAtTime
	// FrameQL query.
	Query OptString
}

func unpackLabelsParams(packed middleware.Parameters) (params LabelsParams) {
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.From = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "until",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Until = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "query",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Query = v.(OptString)
		}
	}
	return params
}

func decodeLabelsParams(args [0]string, argsEscaped bool, r *http.Request) (params LabelsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFromVal AtTime
				if err := func() error {
					var paramsDotFromValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotFromValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotFromVal = AtTime(paramsDotFromValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.From.SetTo(paramsDotFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: until.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "until",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUntilVal AtTime
				if err := func() error {
					var paramsDotUntilValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotUntilValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotUntilVal = AtTime(paramsDotUntilValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.Until.SetTo(paramsDotUntilVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "until",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: query.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "query",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQueryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQueryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Query.SetTo(paramsDotQueryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "query",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// RenderParams is parameters of render operation.
type RenderParams struct {
	// Start of time range in `attime` format.
	From OptAtTime
	// End of time range in `attime` format.
	Until OptAtTime
	// FrameQL query.
	Query    OptString
	Name     OptSegmentKey
	GroupBy  OptString
	MaxNodes OptInt
	// Response format.
	Format RenderFormat
}

func unpackRenderParams(packed middleware.Parameters) (params RenderParams) {
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.From = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "until",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Until = v.(OptAtTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "query",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Query = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Name = v.(OptSegmentKey)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "groupBy",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.GroupBy = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "maxNodes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MaxNodes = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "format",
			In:   "query",
		}
		params.Format = packed[key].(RenderFormat)
	}
	return params
}

func decodeRenderParams(args [0]string, argsEscaped bool, r *http.Request) (params RenderParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFromVal AtTime
				if err := func() error {
					var paramsDotFromValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotFromValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotFromVal = AtTime(paramsDotFromValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.From.SetTo(paramsDotFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: until.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "until",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUntilVal AtTime
				if err := func() error {
					var paramsDotUntilValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotUntilValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotUntilVal = AtTime(paramsDotUntilValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.Until.SetTo(paramsDotUntilVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "until",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: query.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "query",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQueryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQueryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Query.SetTo(paramsDotQueryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "query",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNameVal SegmentKey
				if err := func() error {
					var paramsDotNameValVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotNameValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotNameVal = SegmentKey(paramsDotNameValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.Name.SetTo(paramsDotNameVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: groupBy.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "groupBy",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotGroupByVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotGroupByVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.GroupBy.SetTo(paramsDotGroupByVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupBy",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: maxNodes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "maxNodes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMaxNodesVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMaxNodesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaxNodes.SetTo(paramsDotMaxNodesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "maxNodes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: format.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "format",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Format = RenderFormat(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Format.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "format",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
