openapi: 3.0.3
info:
  title: Grafana Loki API
  version: 2.8.2
externalDocs:
  description: Loki API reference
  url: https://grafana.com/docs/loki/latest/api
servers:
  - url: "http://localhost:3100"
paths:
  /loki/api/v1/query_range:
    get:
      operationId: QueryRange
      description: Query range
      parameters:
        - $ref: "#/components/parameters/GrafanaUser"
        - name: start
          description: |
            The start time for the query as a nanosecond Unix epoch or another supported format.
            Defaults to one hour ago.
          in: query
          schema:
            type: integer
            format: int64
        - name: query
          description: The LogQL query to perform.
          in: query
          required: true
          schema:
            type: string
        - name: step
          description: |
            Query resolution step width in `duration` format or float number of seconds.
            `duration` refers to Prometheus duration strings of the form `[0-9]+[smhdwy]`.
            For example, `5m` refers to a duration of 5 minutes.
            Defaults to a dynamic value based on start and end.
            Only applies to query types which produce a matrix response.
          in: query
          schema:
            $ref: "#/components/schemas/PrometheusDuration"
        - name: limit
          description: |
            The max number of entries to return.
            It defaults to `100`.
            Only applies to query types which produce a stream (log lines) response.
          in: query
          schema:
            type: integer
            maximum: 5000
            minimum: 0
        - name: end
          description: |
            The end time for the query as a nanosecond Unix epoch or another supported format.
            Defaults to now.
          in: query
          schema:
            type: integer
            format: int64
        - name: direction
          description: |
            Determines the sort order of logs.
            Supported values are `forward` or `backward`.
            Defaults to `backward`.
          in: query
          schema:
            $ref: "#/components/schemas/Direction"
      responses:
        "200":
          description: Query response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryResponse"
        default:
          $ref: "#/components/responses/Error"
  /loki/api/v1/labels:
    get:
      operationId: GetLabels
      description: |
        Get labels.
        Used by Grafana to test connection to Loki.
      parameters:
        - $ref: "#/components/parameters/GrafanaUser"
        - name: start
          description: |
            The start time for the query as a nanosecond Unix epoch.
            Defaults to 6 hours ago.
          in: query
          schema:
            type: integer
            format: int64
        - name: end
          description: |
            The end time for the query as a nanosecond Unix epoch.
            Defaults to now.
          in: query
          schema:
            type: integer
            format: int64
        - name: since
          description: |
            A `duration` used to calculate `start` relative to `end`.
            If `end` is in the future, `start` is calculated as this duration before now.
            Any value specified for start supersedes this parameter.
          in: query
          schema:
            $ref: "#/components/schemas/PrometheusDuration"
      responses:
        "200":
          description: Label names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Labels"
        default:
          $ref: "#/components/responses/Error"
  /loki/api/v1/label/{name}/values:
    get:
      operationId: GetLabelValues
      description: Get values of label
      parameters:
        - $ref: "#/components/parameters/GrafanaUser"
        - name: start
          description: |
            The start time for the query as a nanosecond Unix epoch.
            Defaults to 6 hours ago.
          in: query
          schema:
            type: integer
            format: int64
        - name: end
          description: |
            The end time for the query as a nanosecond Unix epoch.
            Defaults to now.
          in: query
          schema:
            type: integer
            format: int64
        - name: since
          description: |
            A `duration` used to calculate `start` relative to `end`.
            If `end` is in the future, `start` is calculated as this duration before now.
            Any value specified for start supersedes this parameter.
          in: query
          schema:
            $ref: "#/components/schemas/PrometheusDuration"
        - name: query
          description: |
            A set of log stream selector that selects the streams to match and return label values for `{name}`.
          in: query
          schema:
            type: string
        - name: name
          description: Label name.
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Label values
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Values"
        default:
          $ref: "#/components/responses/Error"
  /loki/api/v1/series:
    get:
      operationId: Series
      description: Get series
      parameters:
        - name: start
          in: query
          schema:
            type: integer
            format: int64
        - name: end
          in: query
          schema:
            type: integer
            format: int64
        - name: since
          description: |
            A `duration` used to calculate `start` relative to `end`.
            If `end` is in the future, `start` is calculated as this duration before now.
            Any value specified for start supersedes this parameter.
          in: query
          schema:
            $ref: "#/components/schemas/PrometheusDuration"
        - name: match
          in: query
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Keys and values
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Maps"
        default:
          $ref: "#/components/responses/Error"

components:
  parameters:
    # TODO(ernado): extract to separate file? Same for all datasources
    GrafanaUser:
      name: X-Grafana-User
      in: header
      required: false
      description: "Grafana username that is passed to datasource when making requests from Grafana. Used for authentication and authorization."
      schema:
        type: string
  responses:
    Error:
      description: Error while processing request
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Value:
      oneOf:
        - type: string
        - type: number
    Entry:
      type: array
      items:
        $ref: "#/components/schemas/Value"
    Stream:
      type: object
      required:
        - values
      properties:
        stream:
          type: object
          description: Map of labels
          additionalProperties:
            type: string
        metric:
          type: object
          description: Map of labels
          additionalProperties:
            type: string
        values:
          type: array
          items:
            $ref: "#/components/schemas/Entry"
    Streams:
      type: array
      items:
        $ref: "#/components/schemas/Stream"
    Stats:
      type: object
    QueryResponseData:
      type: object
      required:
        - stats
        - resultType
        - result
      properties:
        stats:
          $ref: "#/components/schemas/Stats"
        result:
          $ref: "#/components/schemas/Streams"
        resultType:
          type: string
          enum:
            - streams
            - matrix
    QueryResponse:
      type: object
      required:
        - status
        - data
      properties:
        status:
          type: string
          default: success
        data:
          $ref: "#/components/schemas/QueryResponseData"
    Direction:
      type: string
      enum:
        - BACKWARD
        - FORWARD
        - backward
        - forward
    PrometheusDuration:
      type: string
      pattern: "^[0-9]+[smhdwy]$"
    Labels:
      type: object
      description: Array of label names
      required:
        - data
        - status
      properties:
        data:
          type: array
          items:
            type: string
        status:
          type: string
          default: success
    Values:
      type: object
      description: Array of strings
      required:
        - data
        - status
      properties:
        data:
          type: array
          items:
            type: string
        status:
          type: string
          default: success
    Maps:
      type: object
      description: Array of maps
      required:
        - data
        - status
      properties:
        data:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
        status:
          type: string
          default: success
    Error:
      type: string
