version: "3"

volumes:
  prom:

services:
  clickhouse:
    image: "ghcr.io/go-faster/clickhouse-server:23.12"
    volumes:
      - ./clickhouse.xml:/etc/clickhouse-server/config.d/monitoring.xml
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "127.0.0.1:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30

  prometheus:
    image: "ghcr.io/go-faster/prom/prometheus:v3.1.0"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  oteldb:
    image: ghcr.io/go-faster/oteldb
    build:
      context: ../../../
      dockerfile: deploy.Dockerfile
    command:
      - --config=/etc/otel/cfg.yml
    volumes:
      - ./oteldb.yml:/etc/otel/cfg.yml:ro
    environment:
      - PPROF_ADDR=0.0.0.0:9010
      - OTELDB_STORAGE=ch
      - OTEL_LOG_LEVEL=info
      - OTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_LOGS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_TRACES_SAMPLER=parentbased_always_off
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=go-faster.oteldb
      - GOMAXPROCS=3
      - GOMEMLIMIT=1GiB
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "127.0.0.1:13133/liveness"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "127.0.0.1:9090:9090" # promql
      - "127.0.0.1:9010:9010" # pprof
      - "127.0.0.1:19291:19291" # prometheus remote write
    depends_on:
      - clickhouse

  # Exports traces from clickhouse internal table to otel.
  chotel:
    image: ghcr.io/go-faster/oteldb/chotel
    build:
      context: ../../../
      dockerfile: deploy.chotel.Dockerfile
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=go-faster.oteldb.chotel
      - CHOTEL_SEND_RATE=1s
    depends_on:
      - clickhouse

  tempo:
    image: "ghcr.io/go-faster/tempo"
    command: ["-config.file=/etc/tempo.yml"]
    ports:
      - "127.0.0.1:3200:3200"
    volumes:
      - ./tempo.yml:/etc/tempo.yml

  # https://opentelemetry.io/docs/collector/installation/#docker-compose
  otelcol:
    image: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.89.0"
    volumes:
      - ./otelcol.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "127.0.0.1:4317:4317"
    command:
      - "--config"
      - "/etc/otelcol-contrib/config.yaml"
