apiVersion: 1

datasources:
  - name: "oteldb: TraceQL"
    type: tempo
    access: proxy
    orgId: 1
    url: http://oteldb:3200
    uid: tempo-oteldb
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: promoteldb

  - name: "oteldb: LogQL"
    type: loki
    access: proxy
    orgId: 1
    url: http://oteldb:3100
    uid: loki-oteldb
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    uid: loki
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: promoteldb

  - name: "oteldb: PromQL"
    type: prometheus
    access: proxy
    orgId: 1
    url: http://oteldb:9090
    uid: promoteldb

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      port: 9000
      server: clickhouse
      tlsSkipVerify: true

  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    access: proxy

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    httpMethod: GET
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  # For qryn
  - name: "qryn: LogQL"
    type: loki
    access: proxy
    uid: loki-qryn
    url: http://qryn:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo-qryn
          matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
          name: traceId
          url: '$${__value.raw}'
        - datasourceUid: tempo-qryn
          matcherRegex: "^.*?\"traceID\":\"(\\w+)\".*$"
          name: traceID
          url: '$${__value.raw}'

  - name: "qryn: TraceQL"
    type: tempo
    access: proxy
    uid: tempo-qryn
    url: http://qryn:3100
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki-qryn
        filterByTraceID: false
        spanEndTimeShift: "2000ms"
        spanStartTimeShift: "-2000ms"
        tags: ['job']
      tracesToMetrics:
        datasourceUid: prom-qryn
        tags: ['job']
      serviceMap:
        datasourceUid: prom-qryn
      lokiSearch:
        datasourceUid: loki-qryn

  - name: "qryn: PromQL"
    type: prometheus
    access: proxy
    uid: prom-qryn
    url: http://qryn:3100
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: GET
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
