apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://oteldb:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: promoteldb

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://oteldb:3100
    uid: loki
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: promoteldb

  - name: Prometheus (oteldb)
    type: prometheus
    access: proxy
    orgId: 1
    url: http://oteldb:9090
    uid: promoteldb

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      port: 9000
      server: clickhouse
      tlsSkipVerify: true
