global:
  scrape_interval: 1s

scrape_configs:
  # For PromQL compliance tester
  # https://github.com/prometheus/compliance/tree/main/promql#promql-compliance-tester
  - job_name: 'demo'
    scrape_interval: 1s
    static_configs:
      - targets:
          - 'demo-1:8080'
          - 'demo-2:8080'
          - 'demo-3:8080'

remote_write:
  - url: http://prometheus-remote:9090/api/v1/write
