global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "otelproxy"
    static_configs:
      - targets: ["otelproxy:9000"]
