apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oteldb.fullname" . }}-cfg
  labels:
    {{- include "oteldb.labels" . | nindent 4 }}
data:
  config.yml: |-
    {{ .Values.config | toYaml | nindent 4 }}
