apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oteldb.fullname" . }}
  labels:
    {{- include "oteldb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oteldb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oteldb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oteldb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "oteldb.fullname" . }}-cfg
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: health-check
          readinessProbe:
            httpGet:
              path: /readiness
              port: health-check
          startupProbe:
            httpGet:
              path: /startup
              port: health-check
          volumeMounts:
            - mountPath: /etc/otel/
              name: config
          args:
            - --config=/etc/otel/config.yml
          ports:
            - containerPort: 19291
              protocol: TCP
              name: prom-rw
            - containerPort: 3200
              protocol: TCP
              name: tempo-http
            - containerPort: 9090
              protocol: TCP
              name: prom-http
            - containerPort: 3100
              protocol: TCP
              name: loki-http
            - containerPort: 4317
              protocol: TCP
              name: otlp-grpc
            - containerPort: 4318
              protocol: TCP
              name: otlp-http
            - containerPort: 13133
              protocol: TCP
              name: health-check
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
