version: "3"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9009:9009"
      - "8123:8123"
      - "9000:9000"

  oteldb:
    image: go-faster/oteldb
    build:
      context: ../../../
      dockerfile: Dockerfile
    environment:
      - OTELDB_STORAGE=ch
      - CH_DSN=clickhouse://clickhouse:9000
      - OTEL_LOG_LEVEL=debug
      - METRICS_ADDR=:3201
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=go-faster.oteldb
    ports:
      # - "14268:14268" # jaeger ingest
      - "3200:3200"   # tempo REST API
      # - "9095:9095"   # tempo gRPC API
      - "4317:4317"   # otlp gRPC
      - "4318:4318"   # otlp http
    depends_on:
      - clickhouse

  # Generates traces.
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    environment:
      - ENDPOINT=oteldb:4317
    restart: always
    depends_on:
      - oteldb

  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ../grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_LOG_LEVEL=debug
    ports:
      - "3000:3000"
