// Code generated by ogen, DO NOT EDIT.

package otelbotapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetStatus implements getStatus operation.
//
// Get status.
//
// GET /status
func (UnimplementedHandler) GetStatus(ctx context.Context) (r *GetStatusOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// GET /ping
func (UnimplementedHandler) Ping(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
