// Code generated by ogen, DO NOT EDIT.

package otelbotapi

import (
	"github.com/go-faster/jx"

	std "encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestError_EncodeDecode(t *testing.T) {
	var typ Error
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 Error
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGetStatusOK_EncodeDecode(t *testing.T) {
	var typ GetStatusOK
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetStatusOK
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestSpanID_EncodeDecode(t *testing.T) {
	var typ SpanID
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 SpanID
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestTraceID_EncodeDecode(t *testing.T) {
	var typ TraceID
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 TraceID
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
