// Code generated by ogen, DO NOT EDIT.

package lokiapi

import (
	"fmt"
	"io"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Direction
type Direction string

const (
	DirectionBackward Direction = "backward"
	DirectionForward  Direction = "forward"
)

// MarshalText implements encoding.TextMarshaler.
func (s Direction) MarshalText() ([]byte, error) {
	switch s {
	case DirectionBackward:
		return []byte(s), nil
	case DirectionForward:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Direction) UnmarshalText(data []byte) error {
	switch Direction(data) {
	case DirectionBackward:
		*s = DirectionBackward
		return nil
	case DirectionForward:
		*s = DirectionForward
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type Error string

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/LabelSet
type LabelSet map[string]string

func (s *LabelSet) init() LabelSet {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Array of label names.
// Ref: #/components/schemas/Labels
type Labels struct {
	Data   []string `json:"data"`
	Status string   `json:"status"`
}

// GetData returns the value of Data.
func (s *Labels) GetData() []string {
	return s.Data
}

// GetStatus returns the value of Status.
func (s *Labels) GetStatus() string {
	return s.Status
}

// SetData sets the value of Data.
func (s *Labels) SetData(val []string) {
	s.Data = val
}

// SetStatus sets the value of Status.
func (s *Labels) SetStatus(val string) {
	s.Status = val
}

// Ref: #/components/schemas/LogEntry
type LogEntry struct {
	T uint64
	V string
}

// GetT returns the value of T.
func (s *LogEntry) GetT() uint64 {
	return s.T
}

// GetV returns the value of V.
func (s *LogEntry) GetV() string {
	return s.V
}

// SetT sets the value of T.
func (s *LogEntry) SetT(val uint64) {
	s.T = val
}

// SetV sets the value of V.
func (s *LogEntry) SetV(val string) {
	s.V = val
}

type LokiTime string

// Array of maps.
// Ref: #/components/schemas/Maps
type Maps struct {
	Data   []MapsDataItem `json:"data"`
	Status string         `json:"status"`
}

// GetData returns the value of Data.
func (s *Maps) GetData() []MapsDataItem {
	return s.Data
}

// GetStatus returns the value of Status.
func (s *Maps) GetStatus() string {
	return s.Status
}

// SetData sets the value of Data.
func (s *Maps) SetData(val []MapsDataItem) {
	s.Data = val
}

// SetStatus sets the value of Status.
func (s *Maps) SetStatus(val string) {
	s.Status = val
}

type MapsDataItem map[string]string

func (s *MapsDataItem) init() MapsDataItem {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type Matrix []Series

// Ref: #/components/schemas/MatrixResult
type MatrixResult struct {
	Result Matrix `json:"result"`
	Stats  *Stats `json:"stats"`
}

// GetResult returns the value of Result.
func (s *MatrixResult) GetResult() Matrix {
	return s.Result
}

// GetStats returns the value of Stats.
func (s *MatrixResult) GetStats() *Stats {
	return s.Stats
}

// SetResult sets the value of Result.
func (s *MatrixResult) SetResult(val Matrix) {
	s.Result = val
}

// SetStats sets the value of Stats.
func (s *MatrixResult) SetStats(val *Stats) {
	s.Stats = val
}

type MatrixResultResultType string

const (
	MatrixResultResultTypeMatrix MatrixResultResultType = "matrix"
)

// MarshalText implements encoding.TextMarshaler.
func (s MatrixResultResultType) MarshalText() ([]byte, error) {
	switch s {
	case MatrixResultResultTypeMatrix:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MatrixResultResultType) UnmarshalText(data []byte) error {
	switch MatrixResultResultType(data) {
	case MatrixResultResultTypeMatrix:
		*s = MatrixResultResultTypeMatrix
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptDirection returns new OptDirection with value set to v.
func NewOptDirection(v Direction) OptDirection {
	return OptDirection{
		Value: v,
		Set:   true,
	}
}

// OptDirection is optional Direction.
type OptDirection struct {
	Value Direction
	Set   bool
}

// IsSet returns true if OptDirection was set.
func (o OptDirection) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDirection) Reset() {
	var v Direction
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDirection) SetTo(v Direction) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDirection) Get() (v Direction, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDirection) Or(d Direction) Direction {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLabelSet returns new OptLabelSet with value set to v.
func NewOptLabelSet(v LabelSet) OptLabelSet {
	return OptLabelSet{
		Value: v,
		Set:   true,
	}
}

// OptLabelSet is optional LabelSet.
type OptLabelSet struct {
	Value LabelSet
	Set   bool
}

// IsSet returns true if OptLabelSet was set.
func (o OptLabelSet) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLabelSet) Reset() {
	var v LabelSet
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLabelSet) SetTo(v LabelSet) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLabelSet) Get() (v LabelSet, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLabelSet) Or(d LabelSet) LabelSet {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLokiTime returns new OptLokiTime with value set to v.
func NewOptLokiTime(v LokiTime) OptLokiTime {
	return OptLokiTime{
		Value: v,
		Set:   true,
	}
}

// OptLokiTime is optional LokiTime.
type OptLokiTime struct {
	Value LokiTime
	Set   bool
}

// IsSet returns true if OptLokiTime was set.
func (o OptLokiTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLokiTime) Reset() {
	var v LokiTime
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLokiTime) SetTo(v LokiTime) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLokiTime) Get() (v LokiTime, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLokiTime) Or(d LokiTime) LokiTime {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPrometheusDuration returns new OptPrometheusDuration with value set to v.
func NewOptPrometheusDuration(v PrometheusDuration) OptPrometheusDuration {
	return OptPrometheusDuration{
		Value: v,
		Set:   true,
	}
}

// OptPrometheusDuration is optional PrometheusDuration.
type OptPrometheusDuration struct {
	Value PrometheusDuration
	Set   bool
}

// IsSet returns true if OptPrometheusDuration was set.
func (o OptPrometheusDuration) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPrometheusDuration) Reset() {
	var v PrometheusDuration
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPrometheusDuration) SetTo(v PrometheusDuration) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPrometheusDuration) Get() (v PrometheusDuration, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPrometheusDuration) Or(d PrometheusDuration) PrometheusDuration {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PrometheusDuration string

// Ref: #/components/schemas/PrometheusSamplePair
type PrometheusSamplePair struct {
	T float64
	V string
}

// GetT returns the value of T.
func (s *PrometheusSamplePair) GetT() float64 {
	return s.T
}

// GetV returns the value of V.
func (s *PrometheusSamplePair) GetV() string {
	return s.V
}

// SetT sets the value of T.
func (s *PrometheusSamplePair) SetT(val float64) {
	s.T = val
}

// SetV sets the value of V.
func (s *PrometheusSamplePair) SetV(val string) {
	s.V = val
}

// Ref: #/components/schemas/Push
type Push struct {
	Streams []Stream `json:"streams"`
}

// GetStreams returns the value of Streams.
func (s *Push) GetStreams() []Stream {
	return s.Streams
}

// SetStreams sets the value of Streams.
func (s *Push) SetStreams(val []Stream) {
	s.Streams = val
}

func (*Push) pushReq() {}

// PushNoContent is response for Push operation.
type PushNoContent struct{}

type PushReqApplicationXProtobuf struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s PushReqApplicationXProtobuf) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*PushReqApplicationXProtobuf) pushReq() {}

// Ref: #/components/schemas/QueryResponse
type QueryResponse struct {
	Status string            `json:"status"`
	Data   QueryResponseData `json:"data"`
}

// GetStatus returns the value of Status.
func (s *QueryResponse) GetStatus() string {
	return s.Status
}

// GetData returns the value of Data.
func (s *QueryResponse) GetData() QueryResponseData {
	return s.Data
}

// SetStatus sets the value of Status.
func (s *QueryResponse) SetStatus(val string) {
	s.Status = val
}

// SetData sets the value of Data.
func (s *QueryResponse) SetData(val QueryResponseData) {
	s.Data = val
}

// Ref: #/components/schemas/QueryResponseData
// QueryResponseData represents sum type.
type QueryResponseData struct {
	Type          QueryResponseDataType // switch on this field
	StreamsResult StreamsResult
	VectorResult  VectorResult
	MatrixResult  MatrixResult
}

// QueryResponseDataType is oneOf type of QueryResponseData.
type QueryResponseDataType string

// Possible values for QueryResponseDataType.
const (
	StreamsResultQueryResponseData QueryResponseDataType = "StreamsResult"
	VectorResultQueryResponseData  QueryResponseDataType = "VectorResult"
	MatrixResultQueryResponseData  QueryResponseDataType = "MatrixResult"
)

// IsStreamsResult reports whether QueryResponseData is StreamsResult.
func (s QueryResponseData) IsStreamsResult() bool { return s.Type == StreamsResultQueryResponseData }

// IsVectorResult reports whether QueryResponseData is VectorResult.
func (s QueryResponseData) IsVectorResult() bool { return s.Type == VectorResultQueryResponseData }

// IsMatrixResult reports whether QueryResponseData is MatrixResult.
func (s QueryResponseData) IsMatrixResult() bool { return s.Type == MatrixResultQueryResponseData }

// SetStreamsResult sets QueryResponseData to StreamsResult.
func (s *QueryResponseData) SetStreamsResult(v StreamsResult) {
	s.Type = StreamsResultQueryResponseData
	s.StreamsResult = v
}

// GetStreamsResult returns StreamsResult and true boolean if QueryResponseData is StreamsResult.
func (s QueryResponseData) GetStreamsResult() (v StreamsResult, ok bool) {
	if !s.IsStreamsResult() {
		return v, false
	}
	return s.StreamsResult, true
}

// NewStreamsResultQueryResponseData returns new QueryResponseData from StreamsResult.
func NewStreamsResultQueryResponseData(v StreamsResult) QueryResponseData {
	var s QueryResponseData
	s.SetStreamsResult(v)
	return s
}

// SetVectorResult sets QueryResponseData to VectorResult.
func (s *QueryResponseData) SetVectorResult(v VectorResult) {
	s.Type = VectorResultQueryResponseData
	s.VectorResult = v
}

// GetVectorResult returns VectorResult and true boolean if QueryResponseData is VectorResult.
func (s QueryResponseData) GetVectorResult() (v VectorResult, ok bool) {
	if !s.IsVectorResult() {
		return v, false
	}
	return s.VectorResult, true
}

// NewVectorResultQueryResponseData returns new QueryResponseData from VectorResult.
func NewVectorResultQueryResponseData(v VectorResult) QueryResponseData {
	var s QueryResponseData
	s.SetVectorResult(v)
	return s
}

// SetMatrixResult sets QueryResponseData to MatrixResult.
func (s *QueryResponseData) SetMatrixResult(v MatrixResult) {
	s.Type = MatrixResultQueryResponseData
	s.MatrixResult = v
}

// GetMatrixResult returns MatrixResult and true boolean if QueryResponseData is MatrixResult.
func (s QueryResponseData) GetMatrixResult() (v MatrixResult, ok bool) {
	if !s.IsMatrixResult() {
		return v, false
	}
	return s.MatrixResult, true
}

// NewMatrixResultQueryResponseData returns new QueryResponseData from MatrixResult.
func NewMatrixResultQueryResponseData(v MatrixResult) QueryResponseData {
	var s QueryResponseData
	s.SetMatrixResult(v)
	return s
}

// Ref: #/components/schemas/Series
type Series struct {
	Metric OptLabelSet            `json:"metric"`
	Values []PrometheusSamplePair `json:"values"`
}

// GetMetric returns the value of Metric.
func (s *Series) GetMetric() OptLabelSet {
	return s.Metric
}

// GetValues returns the value of Values.
func (s *Series) GetValues() []PrometheusSamplePair {
	return s.Values
}

// SetMetric sets the value of Metric.
func (s *Series) SetMetric(val OptLabelSet) {
	s.Metric = val
}

// SetValues sets the value of Values.
func (s *Series) SetValues(val []PrometheusSamplePair) {
	s.Values = val
}

// Ref: #/components/schemas/Stats
type Stats struct{}

// Ref: #/components/schemas/Stream
type Stream struct {
	Stream OptLabelSet `json:"stream"`
	Values []LogEntry  `json:"values"`
}

// GetStream returns the value of Stream.
func (s *Stream) GetStream() OptLabelSet {
	return s.Stream
}

// GetValues returns the value of Values.
func (s *Stream) GetValues() []LogEntry {
	return s.Values
}

// SetStream sets the value of Stream.
func (s *Stream) SetStream(val OptLabelSet) {
	s.Stream = val
}

// SetValues sets the value of Values.
func (s *Stream) SetValues(val []LogEntry) {
	s.Values = val
}

type Streams []Stream

// Ref: #/components/schemas/StreamsResult
type StreamsResult struct {
	Result Streams `json:"result"`
	Stats  *Stats  `json:"stats"`
}

// GetResult returns the value of Result.
func (s *StreamsResult) GetResult() Streams {
	return s.Result
}

// GetStats returns the value of Stats.
func (s *StreamsResult) GetStats() *Stats {
	return s.Stats
}

// SetResult sets the value of Result.
func (s *StreamsResult) SetResult(val Streams) {
	s.Result = val
}

// SetStats sets the value of Stats.
func (s *StreamsResult) SetStats(val *Stats) {
	s.Stats = val
}

type StreamsResultResultType string

const (
	StreamsResultResultTypeStreams StreamsResultResultType = "streams"
)

// MarshalText implements encoding.TextMarshaler.
func (s StreamsResultResultType) MarshalText() ([]byte, error) {
	switch s {
	case StreamsResultResultTypeStreams:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *StreamsResultResultType) UnmarshalText(data []byte) error {
	switch StreamsResultResultType(data) {
	case StreamsResultResultTypeStreams:
		*s = StreamsResultResultTypeStreams
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Array of strings.
// Ref: #/components/schemas/Values
type Values struct {
	Data   []string `json:"data"`
	Status string   `json:"status"`
}

// GetData returns the value of Data.
func (s *Values) GetData() []string {
	return s.Data
}

// GetStatus returns the value of Status.
func (s *Values) GetStatus() string {
	return s.Status
}

// SetData sets the value of Data.
func (s *Values) SetData(val []string) {
	s.Data = val
}

// SetStatus sets the value of Status.
func (s *Values) SetStatus(val string) {
	s.Status = val
}

// Ref: #/components/schemas/Vector
type Vector struct {
	Metric OptLabelSet          `json:"metric"`
	Value  PrometheusSamplePair `json:"value"`
}

// GetMetric returns the value of Metric.
func (s *Vector) GetMetric() OptLabelSet {
	return s.Metric
}

// GetValue returns the value of Value.
func (s *Vector) GetValue() PrometheusSamplePair {
	return s.Value
}

// SetMetric sets the value of Metric.
func (s *Vector) SetMetric(val OptLabelSet) {
	s.Metric = val
}

// SetValue sets the value of Value.
func (s *Vector) SetValue(val PrometheusSamplePair) {
	s.Value = val
}

// Ref: #/components/schemas/VectorResult
type VectorResult struct {
	Result []Vector `json:"result"`
	Stats  *Stats   `json:"stats"`
}

// GetResult returns the value of Result.
func (s *VectorResult) GetResult() []Vector {
	return s.Result
}

// GetStats returns the value of Stats.
func (s *VectorResult) GetStats() *Stats {
	return s.Stats
}

// SetResult sets the value of Result.
func (s *VectorResult) SetResult(val []Vector) {
	s.Result = val
}

// SetStats sets the value of Stats.
func (s *VectorResult) SetStats(val *Stats) {
	s.Stats = val
}

type VectorResultResultType string

const (
	VectorResultResultTypeVector VectorResultResultType = "vector"
)

// MarshalText implements encoding.TextMarshaler.
func (s VectorResultResultType) MarshalText() ([]byte, error) {
	switch s {
	case VectorResultResultTypeVector:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *VectorResultResultType) UnmarshalText(data []byte) error {
	switch VectorResultResultType(data) {
	case VectorResultResultTypeVector:
		*s = VectorResultResultTypeVector
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
