version: "3"

volumes:
  prom:
  tempo:

services:
  clickhouse:
    image: "ghcr.io/go-faster/clickhouse-server:23.10"
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ../clickhouse.xml:/etc/clickhouse-server/config.d/monitoring.xml
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', '127.0.0.1:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30

  # Add https://github.com/metrico/qryn for compatibility testing.
  qryn:
    image: qxip/qryn:latest
    ports:
      - "3101:3100"
    restart: on-failure
    environment:
      - CLICKHOUSE_SERVER=clickhouse
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=qryn
    depends_on:
      - clickhouse

  qryn-collector:
    image: ghcr.io/metrico/qryn-otel-collector:latest
    volumes:
      - ./qryncol.yml:/etc/otel/config.yaml
    restart: on-failure
    depends_on:
      - clickhouse

  # Exports traces from clickhouse internal table to otel.
  chotel:
    restart: always
    build:
      context: ../../../
      dockerfile: chotel.Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=service.name=go-faster.oteldb.chotel
    depends_on:
      - clickhouse

  oteldb:
    build:
      context: ../../../
      dockerfile: Dockerfile
    environment:
      - OTELDB_STORAGE=ch
      - CH_DSN=clickhouse://clickhouse:9000
      - OTEL_LOG_LEVEL=debug
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=go-faster.oteldb
    ports:
      - "9090:9090"   # prometheus API
    depends_on:
      - clickhouse

  otelfaker:
    build:
      context: ../../../
      dockerfile: otelfaker.Dockerfile
    environment:
      - OTEL_TARGET=otelcol:4317
    depends_on:
      - oteldb
      - otelcol

  # Generates traces.
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    environment:
      - ENDPOINT=oteldb:4317
    restart: always
    depends_on:
      - oteldb

  # to scrape node-exporter
  # also can remote-write to otelcol
  prometheus:
    image: "ghcr.io/go-faster/prom/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9091:9090"
    restart: unless-stopped
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom:/prometheus

  # For compliance testing.
  demo-1:
    image: "ghcr.io/go-faster/prometheus-demo-service"
  demo-2:
    image: "ghcr.io/go-faster/prometheus-demo-service"
  demo-3:
    image: "ghcr.io/go-faster/prometheus-demo-service"

  # for LogQL
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml

  # https://opentelemetry.io/docs/collector/installation/#docker-compose
  otelcol:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.89.0
    volumes:
      - ./otelcol.yml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - prometheus
      - oteldb
      - node-exporter
      - jaeger
    environment:
      # probably excessive
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4317
    command:
      - '--config'
      - '/etc/otelcol-contrib/config.yaml'
      #  https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/observability.md#how-we-expose-telemetry
      - '--feature-gates=telemetry.useOtelForInternalMetrics'
      - '--feature-gates=telemetry.useOtelWithSDKConfigurationForInternalTelemetry'

  # to produce some metrics
  node-exporter:
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.processes'
      - '--web.max-requests=40'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  # for compatibility testing
  jaeger:
    image: jaegertracing/all-in-one:latest

  tempo:
    image: "ghcr.io/go-faster/tempo"
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - tempo:/tmp/tempo

  grafana:
    image: "ghcr.io/go-faster/grafana:10.0.0"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,traceToMetrics,publicDashboards,tempoApmTable
      - GF_ALERTING_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=debug
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ../grafana/dashboards:/etc/grafana/dashboards:ro
    depends_on:
      - oteldb
      - prometheus
      - otelcol

  # Log generator
  flog:
    image: mingrammer/flog:0.4.3
    # Output fake log in JSON format
    command: [ "--format=json", "--loop", "--delay=100ms"]
    depends_on: [otelcol]
    logging:
      driver: fluentd
      options:
        mode: non-blocking
        fluentd-address: otelcol:24224
        # Allow time for otel-collector to spin up, then forward fluentd logs to the fluentforwarder receiver.
        fluentd-async-connect: "true"
        # Use nanosecond precision
        fluentd-sub-second-precision: "true"
    stop_signal: SIGKILL

  # Telemetry generator
  gen-traces:
    build:
      context: ./opentelemetry-collector-contrib/cmd/telemetrygen/
    command:
      - traces
      - --otlp-endpoint=otelcol:4317
      - --otlp-insecure
      - --rate=10
      - --duration=10000h
    depends_on: [otelcol]
  gen-logs:
    build:
      context: ./opentelemetry-collector-contrib/cmd/telemetrygen/
    command:
      - logs
      - --otlp-endpoint=otelcol:4317
      - --otlp-insecure
      - --rate=10
      - --duration=10000h
    depends_on: [otelcol]
  gen-metrics:
    build:
      context: ./opentelemetry-collector-contrib/cmd/telemetrygen/
    command:
      - metrics
      - --otlp-endpoint=otelcol:4317
      - --otlp-insecure
      - --rate=10
      - --duration=10000h
    depends_on: [otelcol]
