// Code generated by ogen, DO NOT EDIT.

package promapi

// setDefaults set default value of fields.
func (s *Fail) setDefaults() {
	{
		val := string("error")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *LabelValuesResponse) setDefaults() {
	{
		val := string("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *LabelsResponse) setDefaults() {
	{
		val := string("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *MetadataResponse) setDefaults() {
	{
		val := string("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *QueryExemplarsResponse) setDefaults() {
	{
		val := string("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *QueryResponse) setDefaults() {
	{
		val := string("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *RulesResponse) setDefaults() {
	{
		val := string("success")
		s.Status = val
	}
}

// setDefaults set default value of fields.
func (s *SeriesResponse) setDefaults() {
	{
		val := string("success")
		s.Status = val
	}
}
