// Code generated by ogen, DO NOT EDIT.

package promapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/"
			origElem := elem
			if l := len("/api/v1/"); len(elem) >= l && elem[0:l] == "/api/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'l': // Prefix: "label"
				origElem := elem
				if l := len("label"); len(elem) >= l && elem[0:l] == "label" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "label"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/values"
						origElem := elem
						if l := len("/values"); len(elem) >= l && elem[0:l] == "/values" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetLabelValuesRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					}

					elem = origElem
				case 's': // Prefix: "s"
					origElem := elem
					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetLabelsRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handlePostLabelsRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET,POST")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'm': // Prefix: "metadata"
				origElem := elem
				if l := len("metadata"); len(elem) >= l && elem[0:l] == "metadata" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetMetadataRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'q': // Prefix: "query"
				origElem := elem
				if l := len("query"); len(elem) >= l && elem[0:l] == "query" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetQueryRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handlePostQueryRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				switch elem[0] {
				case '_': // Prefix: "_"
					origElem := elem
					if l := len("_"); len(elem) >= l && elem[0:l] == "_" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "exemplars"
						origElem := elem
						if l := len("exemplars"); len(elem) >= l && elem[0:l] == "exemplars" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetQueryExemplarsRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handlePostQueryExemplarsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}

						elem = origElem
					case 'r': // Prefix: "range"
						origElem := elem
						if l := len("range"); len(elem) >= l && elem[0:l] == "range" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetQueryRangeRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handlePostQueryRangeRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'r': // Prefix: "rules"
				origElem := elem
				if l := len("rules"); len(elem) >= l && elem[0:l] == "rules" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetRulesRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 's': // Prefix: "series"
				origElem := elem
				if l := len("series"); len(elem) >= l && elem[0:l] == "series" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetSeriesRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handlePostSeriesRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v1/"
			origElem := elem
			if l := len("/api/v1/"); len(elem) >= l && elem[0:l] == "/api/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'l': // Prefix: "label"
				origElem := elem
				if l := len("label"); len(elem) >= l && elem[0:l] == "label" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"
					origElem := elem
					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "label"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/values"
						origElem := elem
						if l := len("/values"); len(elem) >= l && elem[0:l] == "/values" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetLabelValuesOperation
								r.summary = ""
								r.operationID = "getLabelValues"
								r.pathPattern = "/api/v1/label/{label}/values"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}

					elem = origElem
				case 's': // Prefix: "s"
					origElem := elem
					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetLabelsOperation
							r.summary = ""
							r.operationID = "getLabels"
							r.pathPattern = "/api/v1/labels"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = PostLabelsOperation
							r.summary = ""
							r.operationID = "postLabels"
							r.pathPattern = "/api/v1/labels"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'm': // Prefix: "metadata"
				origElem := elem
				if l := len("metadata"); len(elem) >= l && elem[0:l] == "metadata" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetMetadataOperation
						r.summary = ""
						r.operationID = "getMetadata"
						r.pathPattern = "/api/v1/metadata"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'q': // Prefix: "query"
				origElem := elem
				if l := len("query"); len(elem) >= l && elem[0:l] == "query" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = GetQueryOperation
						r.summary = ""
						r.operationID = "getQuery"
						r.pathPattern = "/api/v1/query"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = PostQueryOperation
						r.summary = ""
						r.operationID = "postQuery"
						r.pathPattern = "/api/v1/query"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '_': // Prefix: "_"
					origElem := elem
					if l := len("_"); len(elem) >= l && elem[0:l] == "_" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'e': // Prefix: "exemplars"
						origElem := elem
						if l := len("exemplars"); len(elem) >= l && elem[0:l] == "exemplars" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetQueryExemplarsOperation
								r.summary = ""
								r.operationID = "getQueryExemplars"
								r.pathPattern = "/api/v1/query_exemplars"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = PostQueryExemplarsOperation
								r.summary = ""
								r.operationID = "postQueryExemplars"
								r.pathPattern = "/api/v1/query_exemplars"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					case 'r': // Prefix: "range"
						origElem := elem
						if l := len("range"); len(elem) >= l && elem[0:l] == "range" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetQueryRangeOperation
								r.summary = ""
								r.operationID = "getQueryRange"
								r.pathPattern = "/api/v1/query_range"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = PostQueryRangeOperation
								r.summary = ""
								r.operationID = "postQueryRange"
								r.pathPattern = "/api/v1/query_range"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'r': // Prefix: "rules"
				origElem := elem
				if l := len("rules"); len(elem) >= l && elem[0:l] == "rules" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetRulesOperation
						r.summary = ""
						r.operationID = "getRules"
						r.pathPattern = "/api/v1/rules"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 's': // Prefix: "series"
				origElem := elem
				if l := len("series"); len(elem) >= l && elem[0:l] == "series" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetSeriesOperation
						r.summary = ""
						r.operationID = "getSeries"
						r.pathPattern = "/api/v1/series"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = PostSeriesOperation
						r.summary = ""
						r.operationID = "postSeries"
						r.pathPattern = "/api/v1/series"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	return r, false
}
