// Code generated by ogen, DO NOT EDIT.

package promapi

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type Error string

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/InstantQueryData
// InstantQueryData represents sum type.
type InstantQueryData struct {
	Type   InstantQueryDataType // switch on this field
	Matrix Matrix
}

// InstantQueryDataType is oneOf type of InstantQueryData.
type InstantQueryDataType string

// Possible values for InstantQueryDataType.
const (
	MatrixInstantQueryData InstantQueryDataType = "Matrix"
)

// IsMatrix reports whether InstantQueryData is Matrix.
func (s InstantQueryData) IsMatrix() bool { return s.Type == MatrixInstantQueryData }

// SetMatrix sets InstantQueryData to Matrix.
func (s *InstantQueryData) SetMatrix(v Matrix) {
	s.Type = MatrixInstantQueryData
	s.Matrix = v
}

// GetMatrix returns Matrix and true boolean if InstantQueryData is Matrix.
func (s InstantQueryData) GetMatrix() (v Matrix, ok bool) {
	if !s.IsMatrix() {
		return v, false
	}
	return s.Matrix, true
}

// NewMatrixInstantQueryData returns new InstantQueryData from Matrix.
func NewMatrixInstantQueryData(v Matrix) InstantQueryData {
	var s InstantQueryData
	s.SetMatrix(v)
	return s
}

// Ref: #/components/schemas/InstantQueryResponse
type InstantQueryResponse struct {
	Status string           `json:"status"`
	Data   InstantQueryData `json:"data"`
}

// GetStatus returns the value of Status.
func (s *InstantQueryResponse) GetStatus() string {
	return s.Status
}

// GetData returns the value of Data.
func (s *InstantQueryResponse) GetData() InstantQueryData {
	return s.Data
}

// SetStatus sets the value of Status.
func (s *InstantQueryResponse) SetStatus(val string) {
	s.Status = val
}

// SetData sets the value of Data.
func (s *InstantQueryResponse) SetData(val InstantQueryData) {
	s.Data = val
}

// Ref: #/components/schemas/Matrix
type Matrix struct{}
