// Code generated by ogen, DO NOT EDIT.

package promapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetLabelValuesOperation     OperationName = "GetLabelValues"
	GetLabelsOperation          OperationName = "GetLabels"
	GetMetadataOperation        OperationName = "GetMetadata"
	GetQueryOperation           OperationName = "GetQuery"
	GetQueryExemplarsOperation  OperationName = "GetQueryExemplars"
	GetQueryRangeOperation      OperationName = "GetQueryRange"
	GetRulesOperation           OperationName = "GetRules"
	GetSeriesOperation          OperationName = "GetSeries"
	PostLabelsOperation         OperationName = "PostLabels"
	PostQueryOperation          OperationName = "PostQuery"
	PostQueryExemplarsOperation OperationName = "PostQueryExemplars"
	PostQueryRangeOperation     OperationName = "PostQueryRange"
	PostSeriesOperation         OperationName = "PostSeries"
)
