apiVersion: 1

datasources:
  - name: "PromQL"
    type: prometheus
    access: proxy
    orgId: 1
    isDefault: true
    url: http://oteldb:9090
    uid: prom-oteldb

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      port: 9000
      server: clickhouse
      tlsSkipVerify: true
