CREATE TABLE IF NOT EXISTS `metrics_exemplars`
(
	`name`                                          LowCardinality(String),
	`name_normalized`                               LowCardinality(String),
	`timestamp`                                     DateTime64(9)          CODEC(Delta, ZSTD(1)),
	`filtered_attributes`                           String,
	`exemplar_timestamp`                            DateTime64(9)          CODEC(Delta, ZSTD(1)),
	`value`                                         Float64,
	`trace_id`                                      FixedString(16),
	`span_id`                                       FixedString(8),
	-- attribute attributes
	`attribute`                                     LowCardinality(String),
	`attr_k8s_container_restart_count`              Int64,
	`code_column`                                   Int64,
	`code_lineno`                                   Int64,
	`db_cassandra_page_size`                        Int64,
	`db_cassandra_speculative_execution_count`      Int64,
	`db_cosmosdb_request_content_length`            Int64,
	`db_cosmosdb_status_code`                       Int64,
	`db_cosmosdb_sub_status_code`                   Int64,
	`db_redis_database_index`                       Int64,
	`gcp_cloud_run_job_task_index`                  Int64,
	`http_request_body_size`                        Int64,
	`http_request_resend_count`                     Int64,
	`http_response_body_size`                       Int64,
	`http_response_status_code`                     Int64,
	`message_compressed_size`                       Int64,
	`message_id`                                    Int64,
	`message_uncompressed_size`                     Int64,
	`messaging_batch_message_count`                 Int64,
	`messaging_kafka_destination_partition`         Int64,
	`messaging_kafka_message_offset`                Int64,
	`messaging_message_body_size`                   Int64,
	`messaging_message_envelope_size`               Int64,
	`messaging_rocketmq_message_delay_time_level`   Int64,
	`messaging_rocketmq_message_delivery_timestamp` Int64,
	`rpc_jsonrpc_error_code`                        Int64,
	`system_cpu_logical_number`                     Int64,
	`thread_id`                                     Int64,
	`attr_k8s_cluster_name`                         String,
	`attr_k8s_container_name`                       String,
	`attr_k8s_cronjob_name`                         String,
	`attr_k8s_daemonset_name`                       String,
	`attr_k8s_deployment_name`                      String,
	`attr_k8s_job_name`                             String,
	`attr_k8s_namespace_name`                       String,
	`attr_k8s_node_name`                            String,
	`attr_k8s_pod_name`                             String,
	`attr_k8s_replicaset_name`                      String,
	`attr_k8s_statefulset_name`                     String,
	`aws_ecs_cluster_arn`                           String,
	`aws_ecs_container_arn`                         String,
	`aws_ecs_launchtype`                            Enum8('' = 0, 'ec2' = 1, 'fargate' = 2),
	`aws_ecs_task_arn`                              String,
	`aws_ecs_task_family`                           String,
	`aws_ecs_task_revision`                         String,
	`aws_eks_cluster_arn`                           String,
	`aws_lambda_invoked_arn`                        String,
	`client_address`                                String,
	`cloudevents_event_id`                          String,
	`cloudevents_event_source`                      String,
	`cloudevents_event_spec_version`                String,
	`cloudevents_event_subject`                     String,
	`cloudevents_event_type`                        String,
	`code_filepath`                                 String,
	`code_function`                                 String,
	`code_namespace`                                String,
	`code_stacktrace`                               String,
	`db_cassandra_consistency_level`                Enum8('' = 0, 'all' = 1, 'each_quorum' = 2, 'quorum' = 3, 'local_quorum' = 4, 'one' = 5, 'two' = 6, 'three' = 7, 'local_one' = 8, 'any' = 9, 'serial' = 10, 'local_serial' = 11),
	`db_cassandra_coordinator_dc`                   String,
	`db_cassandra_coordinator_id`                   String,
	`db_cassandra_table`                            String,
	`db_connection_string`                          String,
	`db_cosmosdb_client_id`                         String,
	`db_cosmosdb_connection_mode`                   Enum8('' = 0, 'gateway' = 1, 'direct' = 2),
	`db_cosmosdb_container`                         String,
	`db_cosmosdb_operation_type`                    String,
	`db_elasticsearch_cluster_name`                 String,
	`db_elasticsearch_node_name`                    String,
	`db_instance_id`                                String,
	`db_jdbc_driver_classname`                      String,
	`db_mongodb_collection`                         String,
	`db_mssql_instance_name`                        String,
	`db_name`                                       String,
	`db_operation`                                  String,
	`db_sql_table`                                  String,
	`db_statement`                                  String,
	`db_system`                                     String,
	`db_user`                                       String,
	`destination_address`                           String,
	`disk_io_direction`                             Enum8('' = 0, 'read' = 1, 'write' = 2),
	`enduser_id`                                    String,
	`enduser_role`                                  String,
	`enduser_scope`                                 String,
	`error_type`                                    String,
	`event_name`                                    String,
	`exception_message`                             String,
	`exception_stacktrace`                          String,
	`exception_type`                                String,
	`feature_flag_key`                              String,
	`feature_flag_provider_name`                    String,
	`feature_flag_variant`                          String,
	`gcp_cloud_run_job_execution`                   String,
	`gcp_gce_instance_hostname`                     String,
	`gcp_gce_instance_name`                         String,
	`http_request_method`                           String,
	`http_request_method_original`                  String,
	`http_route`                                    String,
	`ios_state`                                     Enum8('' = 0, 'active' = 1, 'inactive' = 2, 'background' = 3, 'foreground' = 4, 'terminate' = 5),
	`jvm_buffer_pool_name`                          String,
	`jvm_gc_action`                                 String,
	`jvm_gc_name`                                   String,
	`jvm_memory_pool_name`                          String,
	`jvm_memory_type`                               Enum8('' = 0, 'heap' = 1, 'non_heap' = 2),
	`jvm_thread_state`                              Enum8('' = 0, 'new' = 1, 'runnable' = 2, 'blocked' = 3, 'waiting' = 4, 'timed_waiting' = 5, 'terminated' = 6),
	`log_file_name`                                 String,
	`log_file_name_resolved`                        String,
	`log_file_path`                                 String,
	`log_file_path_resolved`                        String,
	`log_iostream`                                  Enum8('' = 0, 'stdout' = 1, 'stderr' = 2),
	`log_record_uid`                                String,
	`message_type`                                  Enum8('' = 0, 'SENT' = 1, 'RECEIVED' = 2),
	`messaging_client_id`                           String,
	`messaging_destination_name`                    String,
	`messaging_destination_publish_name`            String,
	`messaging_destination_template`                String,
	`messaging_gcp_pubsub_message_ordering_key`     String,
	`messaging_kafka_consumer_group`                String,
	`messaging_kafka_message_key`                   String,
	`messaging_message_conversation_id`             String,
	`messaging_message_id`                          String,
	`messaging_operation`                           String,
	`messaging_rabbitmq_destination_routing_key`    String,
	`messaging_rocketmq_client_group`               String,
	`messaging_rocketmq_consumption_model`          Enum8('' = 0, 'clustering' = 1, 'broadcasting' = 2),
	`messaging_rocketmq_message_group`              String,
	`messaging_rocketmq_message_tag`                String,
	`messaging_rocketmq_message_type`               Enum8('' = 0, 'normal' = 1, 'fifo' = 2, 'delay' = 3, 'transaction' = 4),
	`messaging_rocketmq_namespace`                  String,
	`messaging_system`                              String,
	`network_carrier_icc`                           String,
	`network_carrier_mcc`                           String,
	`network_carrier_mnc`                           String,
	`network_carrier_name`                          String,
	`network_connection_subtype`                    String,
	`network_connection_type`                       String,
	`network_io_direction`                          Enum8('' = 0, 'transmit' = 1, 'receive' = 2),
	`network_local_address`                         String,
	`network_peer_address`                          String,
	`network_protocol_name`                         String,
	`network_protocol_version`                      String,
	`network_transport`                             String,
	`network_type`                                  String,
	`oci_manifest_digest`                           String,
	`opentracing_ref_type`                          Enum8('' = 0, 'child_of' = 1, 'follows_from' = 2),
	`otel_scope_name`                               String,
	`otel_scope_version`                            String,
	`otel_status_code`                              Enum8('' = 0, 'OK' = 1, 'ERROR' = 2),
	`otel_status_description`                       String,
	`peer_service`                                  String,
	`pool_name`                                     String,
	`rpc_connect_rpc_error_code`                    Enum8('' = 0, 'cancelled' = 1, 'unknown' = 2, 'invalid_argument' = 3, 'deadline_exceeded' = 4, 'not_found' = 5, 'already_exists' = 6, 'permission_denied' = 7, 'resource_exhausted' = 8, 'failed_precondition' = 9, 'aborted' = 10, 'out_of_range' = 11, 'unimplemented' = 12, 'internal' = 13, 'unavailable' = 14, 'data_loss' = 15, 'unauthenticated' = 16),
	`rpc_jsonrpc_error_message`                     String,
	`rpc_jsonrpc_request_id`                        String,
	`rpc_jsonrpc_version`                           String,
	`rpc_method`                                    String,
	`rpc_service`                                   String,
	`rpc_system`                                    String,
	`server_address`                                String,
	`session_id`                                    String,
	`session_previous_id`                           String,
	`source_address`                                String,
	`state`                                         Enum8('' = 0, 'idle' = 1, 'used' = 2),
	`system_cpu_state`                              String,
	`system_device`                                 String,
	`system_filesystem_mode`                        String,
	`system_filesystem_mountpoint`                  String,
	`system_filesystem_state`                       Enum8('' = 0, 'used' = 1, 'free' = 2, 'reserved' = 3),
	`system_filesystem_type`                        String,
	`system_memory_state`                           String,
	`system_network_state`                          Enum8('' = 0, 'close' = 1, 'close_wait' = 2, 'closing' = 3, 'delete' = 4, 'established' = 5, 'fin_wait_1' = 6, 'fin_wait_2' = 7, 'last_ack' = 8, 'listen' = 9, 'syn_recv' = 10, 'syn_sent' = 11, 'time_wait' = 12),
	`system_paging_direction`                       Enum8('' = 0, 'in' = 1, 'out' = 2),
	`system_paging_state`                           Enum8('' = 0, 'used' = 1, 'free' = 2),
	`system_paging_type`                            Enum8('' = 0, 'major' = 1, 'minor' = 2),
	`system_processes_status`                       String,
	`thread_name`                                   String,
	`tls_cipher`                                    String,
	`tls_client_certificate`                        String,
	`tls_client_hash_md5`                           String,
	`tls_client_hash_sha1`                          String,
	`tls_client_hash_sha256`                        String,
	`tls_client_issuer`                             String,
	`tls_client_ja3`                                String,
	`tls_client_not_after`                          String,
	`tls_client_not_before`                         String,
	`tls_client_server_name`                        String,
	`tls_client_subject`                            String,
	`tls_curve`                                     String,
	`tls_next_protocol`                             String,
	`tls_protocol_name`                             String,
	`tls_protocol_version`                          String,
	`tls_server_certificate`                        String,
	`tls_server_hash_md5`                           String,
	`tls_server_hash_sha1`                          String,
	`tls_server_hash_sha256`                        String,
	`tls_server_issuer`                             String,
	`tls_server_ja3s`                               String,
	`tls_server_not_after`                          String,
	`tls_server_not_before`                         String,
	`tls_server_subject`                            String,
	`url_fragment`                                  String,
	`url_full`                                      String,
	`url_path`                                      String,
	`url_query`                                     String,
	`url_scheme`                                    String,
	`user_agent_original`                           String,
	`attr_k8s_cluster_uid`                          UUID,
	`attr_k8s_cronjob_uid`                          UUID,
	`attr_k8s_daemonset_uid`                        UUID,
	`attr_k8s_deployment_uid`                       UUID,
	`attr_k8s_job_uid`                              UUID,
	`attr_k8s_node_uid`                             UUID,
	`attr_k8s_pod_uid`                              UUID,
	`attr_k8s_replicaset_uid`                       UUID,
	`attr_k8s_statefulset_uid`                      UUID,
	-- end
	-- resource attributes
	`resource`                                      LowCardinality(String),
	`faas_max_memory`                               Int64,
	`host_cpu_cache_l2_size`                        Int64,
	`host_cpu_stepping`                             Int64,
	`process_parent_pid`                            Int64,
	`process_pid`                                   Int64,
	`res_k8s_container_restart_count`               Int64,
	`android_os_api_level`                          LowCardinality(String),
	`android_state`                                 Enum8('' = 0, 'created' = 1, 'background' = 2, 'foreground' = 3),
	`browser_language`                              LowCardinality(String),
	`browser_platform`                              LowCardinality(String),
	`cloud_account_id`                              LowCardinality(String),
	`cloud_availability_zone`                       LowCardinality(String),
	`cloud_platform`                                LowCardinality(String),
	`cloud_provider`                                LowCardinality(String),
	`cloud_region`                                  LowCardinality(String),
	`cloud_resource_id`                             LowCardinality(String),
	`container_command`                             LowCardinality(String),
	`container_command_line`                        LowCardinality(String),
	`container_id`                                  LowCardinality(String),
	`container_image_id`                            LowCardinality(String),
	`container_image_name`                          LowCardinality(String),
	`container_name`                                LowCardinality(String),
	`container_runtime`                             LowCardinality(String),
	`deployment_environment`                        LowCardinality(String),
	`device_id`                                     LowCardinality(String),
	`device_manufacturer`                           LowCardinality(String),
	`device_model_identifier`                       LowCardinality(String),
	`device_model_name`                             LowCardinality(String),
	`faas_cron`                                     LowCardinality(String),
	`faas_document_collection`                      LowCardinality(String),
	`faas_document_name`                            LowCardinality(String),
	`faas_document_operation`                       LowCardinality(String),
	`faas_instance`                                 LowCardinality(String),
	`faas_invocation_id`                            LowCardinality(String),
	`faas_invoked_name`                             LowCardinality(String),
	`faas_invoked_provider`                         LowCardinality(String),
	`faas_invoked_region`                           LowCardinality(String),
	`faas_name`                                     LowCardinality(String),
	`faas_trigger`                                  Enum8('' = 0, 'datasource' = 1, 'http' = 2, 'pubsub' = 3, 'timer' = 4, 'other' = 5),
	`faas_version`                                  LowCardinality(String),
	`heroku_app_id`                                 LowCardinality(String),
	`heroku_release_commit`                         LowCardinality(String),
	`heroku_release_creation_timestamp`             LowCardinality(String),
	`host_arch`                                     LowCardinality(String),
	`host_cpu_family`                               LowCardinality(String),
	`host_cpu_model_id`                             LowCardinality(String),
	`host_cpu_model_name`                           LowCardinality(String),
	`host_cpu_vendor_id`                            LowCardinality(String),
	`host_id`                                       LowCardinality(String),
	`host_image_id`                                 LowCardinality(String),
	`host_image_name`                               LowCardinality(String),
	`host_image_version`                            LowCardinality(String),
	`host_name`                                     LowCardinality(String),
	`host_type`                                     LowCardinality(String),
	`os_build_id`                                   LowCardinality(String),
	`os_description`                                LowCardinality(String),
	`os_name`                                       LowCardinality(String),
	`os_type`                                       LowCardinality(String),
	`os_version`                                    LowCardinality(String),
	`process_command`                               LowCardinality(String),
	`process_command_line`                          LowCardinality(String),
	`process_executable_name`                       LowCardinality(String),
	`process_executable_path`                       LowCardinality(String),
	`process_owner`                                 LowCardinality(String),
	`process_runtime_description`                   LowCardinality(String),
	`process_runtime_name`                          LowCardinality(String),
	`process_runtime_version`                       LowCardinality(String),
	`res_k8s_cluster_name`                          LowCardinality(String),
	`res_k8s_container_name`                        LowCardinality(String),
	`res_k8s_cronjob_name`                          LowCardinality(String),
	`res_k8s_daemonset_name`                        LowCardinality(String),
	`res_k8s_deployment_name`                       LowCardinality(String),
	`res_k8s_job_name`                              LowCardinality(String),
	`res_k8s_namespace_name`                        LowCardinality(String),
	`res_k8s_node_name`                             LowCardinality(String),
	`res_k8s_pod_name`                              LowCardinality(String),
	`res_k8s_replicaset_name`                       LowCardinality(String),
	`res_k8s_statefulset_name`                      LowCardinality(String),
	`service_version`                               LowCardinality(String),
	`telemetry_distro_name`                         LowCardinality(String),
	`telemetry_distro_version`                      LowCardinality(String),
	`telemetry_sdk_language`                        LowCardinality(String),
	`telemetry_sdk_name`                            LowCardinality(String),
	`telemetry_sdk_version`                         LowCardinality(String),
	`webengine_description`                         LowCardinality(String),
	`webengine_name`                                LowCardinality(String),
	`webengine_version`                             LowCardinality(String),
	`res_k8s_cluster_uid`                           UUID,
	`res_k8s_cronjob_uid`                           UUID,
	`res_k8s_daemonset_uid`                         UUID,
	`res_k8s_deployment_uid`                        UUID,
	`res_k8s_job_uid`                               UUID,
	`res_k8s_node_uid`                              UUID,
	`res_k8s_pod_uid`                               UUID,
	`res_k8s_replicaset_uid`                        UUID,
	`res_k8s_statefulset_uid`                       UUID,
	-- end
	-- scope attributes
	`scope`                                         LowCardinality(String),
	-- end
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (`name_normalized`, `resource`, `attribute`, `timestamp`)
