CREATE TABLE IF NOT EXISTS `metrics_exemplars`
(
	`name`                                               LowCardinality(String),
	`name_normalized`                                    LowCardinality(String),
	`timestamp`                                          DateTime64(9)          CODEC(Delta, ZSTD(1)),
	`filtered_attributes`                                String,
	`exemplar_timestamp`                                 DateTime64(9)          CODEC(Delta, ZSTD(1)),
	`value`                                              Float64,
	`trace_id`                                           FixedString(16),
	`span_id`                                            FixedString(8),
	-- attribute attributes
	`attribute`                                          LowCardinality(String),
	`attr_code_column`                                   Int64,
	`attr_code_lineno`                                   Int64,
	`attr_db_cassandra_page_size`                        Int64,
	`attr_db_cassandra_speculative_execution_count`      Int64,
	`attr_db_cosmosdb_request_content_length`            Int64,
	`attr_db_cosmosdb_status_code`                       Int64,
	`attr_db_cosmosdb_sub_status_code`                   Int64,
	`attr_db_redis_database_index`                       Int64,
	`attr_gcp_cloud_run_job_task_index`                  Int64,
	`attr_http_request_body_size`                        Int64,
	`attr_http_request_resend_count`                     Int64,
	`attr_http_response_body_size`                       Int64,
	`attr_http_response_status_code`                     Int64,
	`attr_k8s_container_restart_count`                   Int64,
	`attr_message_compressed_size`                       Int64,
	`attr_message_id`                                    Int64,
	`attr_message_uncompressed_size`                     Int64,
	`attr_messaging_batch_message_count`                 Int64,
	`attr_messaging_kafka_destination_partition`         Int64,
	`attr_messaging_kafka_message_offset`                Int64,
	`attr_messaging_message_body_size`                   Int64,
	`attr_messaging_message_envelope_size`               Int64,
	`attr_messaging_rocketmq_message_delay_time_level`   Int64,
	`attr_messaging_rocketmq_message_delivery_timestamp` Int64,
	`attr_rpc_jsonrpc_error_code`                        Int64,
	`attr_system_cpu_logical_number`                     Int64,
	`attr_thread_id`                                     Int64,
	`attr_aws_ecs_cluster_arn`                           String,
	`attr_aws_ecs_container_arn`                         String,
	`attr_aws_ecs_launchtype`                            Enum8('ec2' = 0, 'fargate' = 1),
	`attr_aws_ecs_task_arn`                              String,
	`attr_aws_ecs_task_family`                           String,
	`attr_aws_ecs_task_revision`                         String,
	`attr_aws_eks_cluster_arn`                           String,
	`attr_aws_lambda_invoked_arn`                        String,
	`attr_client_address`                                String,
	`attr_cloudevents_event_id`                          String,
	`attr_cloudevents_event_source`                      String,
	`attr_cloudevents_event_spec_version`                String,
	`attr_cloudevents_event_subject`                     String,
	`attr_cloudevents_event_type`                        String,
	`attr_code_filepath`                                 String,
	`attr_code_function`                                 String,
	`attr_code_namespace`                                String,
	`attr_code_stacktrace`                               String,
	`attr_db_cassandra_consistency_level`                Enum8('all' = 0, 'each_quorum' = 1, 'quorum' = 2, 'local_quorum' = 3, 'one' = 4, 'two' = 5, 'three' = 6, 'local_one' = 7, 'any' = 8, 'serial' = 9, 'local_serial' = 10),
	`attr_db_cassandra_coordinator_dc`                   String,
	`attr_db_cassandra_coordinator_id`                   String,
	`attr_db_cassandra_table`                            String,
	`attr_db_connection_string`                          String,
	`attr_db_cosmosdb_client_id`                         String,
	`attr_db_cosmosdb_connection_mode`                   Enum8('gateway' = 0, 'direct' = 1),
	`attr_db_cosmosdb_container`                         String,
	`attr_db_cosmosdb_operation_type`                    String,
	`attr_db_elasticsearch_cluster_name`                 String,
	`attr_db_elasticsearch_node_name`                    String,
	`attr_db_instance_id`                                String,
	`attr_db_jdbc_driver_classname`                      String,
	`attr_db_mongodb_collection`                         String,
	`attr_db_mssql_instance_name`                        String,
	`attr_db_name`                                       String,
	`attr_db_operation`                                  String,
	`attr_db_sql_table`                                  String,
	`attr_db_statement`                                  String,
	`attr_db_system`                                     String,
	`attr_db_user`                                       String,
	`attr_destination_address`                           String,
	`attr_disk_io_direction`                             Enum8('read' = 0, 'write' = 1),
	`attr_enduser_id`                                    String,
	`attr_enduser_role`                                  String,
	`attr_enduser_scope`                                 String,
	`attr_error_type`                                    String,
	`attr_event_name`                                    String,
	`attr_exception_message`                             String,
	`attr_exception_stacktrace`                          String,
	`attr_exception_type`                                String,
	`attr_feature_flag_key`                              String,
	`attr_feature_flag_provider_name`                    String,
	`attr_feature_flag_variant`                          String,
	`attr_gcp_cloud_run_job_execution`                   String,
	`attr_gcp_gce_instance_hostname`                     String,
	`attr_gcp_gce_instance_name`                         String,
	`attr_http_request_method`                           String,
	`attr_http_request_method_original`                  String,
	`attr_http_route`                                    String,
	`attr_ios_state`                                     Enum8('active' = 0, 'inactive' = 1, 'background' = 2, 'foreground' = 3, 'terminate' = 4),
	`attr_jvm_buffer_pool_name`                          String,
	`attr_jvm_gc_action`                                 String,
	`attr_jvm_gc_name`                                   String,
	`attr_jvm_memory_pool_name`                          String,
	`attr_jvm_memory_type`                               Enum8('heap' = 0, 'non_heap' = 1),
	`attr_jvm_thread_state`                              Enum8('new' = 0, 'runnable' = 1, 'blocked' = 2, 'waiting' = 3, 'timed_waiting' = 4, 'terminated' = 5),
	`attr_k8s_cluster_name`                              String,
	`attr_k8s_container_name`                            String,
	`attr_k8s_cronjob_name`                              String,
	`attr_k8s_daemonset_name`                            String,
	`attr_k8s_deployment_name`                           String,
	`attr_k8s_job_name`                                  String,
	`attr_k8s_namespace_name`                            String,
	`attr_k8s_node_name`                                 String,
	`attr_k8s_pod_name`                                  String,
	`attr_k8s_replicaset_name`                           String,
	`attr_k8s_statefulset_name`                          String,
	`attr_log_file_name`                                 String,
	`attr_log_file_name_resolved`                        String,
	`attr_log_file_path`                                 String,
	`attr_log_file_path_resolved`                        String,
	`attr_log_iostream`                                  Enum8('stdout' = 0, 'stderr' = 1),
	`attr_log_record_uid`                                String,
	`attr_message_type`                                  Enum8('SENT' = 0, 'RECEIVED' = 1),
	`attr_messaging_client_id`                           String,
	`attr_messaging_destination_name`                    String,
	`attr_messaging_destination_publish_name`            String,
	`attr_messaging_destination_template`                String,
	`attr_messaging_gcp_pubsub_message_ordering_key`     String,
	`attr_messaging_kafka_consumer_group`                String,
	`attr_messaging_kafka_message_key`                   String,
	`attr_messaging_message_conversation_id`             String,
	`attr_messaging_message_id`                          String,
	`attr_messaging_operation`                           String,
	`attr_messaging_rabbitmq_destination_routing_key`    String,
	`attr_messaging_rocketmq_client_group`               String,
	`attr_messaging_rocketmq_consumption_model`          Enum8('clustering' = 0, 'broadcasting' = 1),
	`attr_messaging_rocketmq_message_group`              String,
	`attr_messaging_rocketmq_message_tag`                String,
	`attr_messaging_rocketmq_message_type`               Enum8('normal' = 0, 'fifo' = 1, 'delay' = 2, 'transaction' = 3),
	`attr_messaging_rocketmq_namespace`                  String,
	`attr_messaging_system`                              String,
	`attr_network_carrier_icc`                           String,
	`attr_network_carrier_mcc`                           String,
	`attr_network_carrier_mnc`                           String,
	`attr_network_carrier_name`                          String,
	`attr_network_connection_subtype`                    String,
	`attr_network_connection_type`                       String,
	`attr_network_io_direction`                          Enum8('transmit' = 0, 'receive' = 1),
	`attr_network_local_address`                         String,
	`attr_network_peer_address`                          String,
	`attr_network_protocol_name`                         String,
	`attr_network_protocol_version`                      String,
	`attr_network_transport`                             String,
	`attr_network_type`                                  String,
	`attr_oci_manifest_digest`                           String,
	`attr_opentracing_ref_type`                          Enum8('child_of' = 0, 'follows_from' = 1),
	`attr_otel_scope_name`                               String,
	`attr_otel_scope_version`                            String,
	`attr_otel_status_code`                              Enum8('OK' = 0, 'ERROR' = 1),
	`attr_otel_status_description`                       String,
	`attr_peer_service`                                  String,
	`attr_pool_name`                                     String,
	`attr_rpc_connect_rpc_error_code`                    Enum8('cancelled' = 0, 'unknown' = 1, 'invalid_argument' = 2, 'deadline_exceeded' = 3, 'not_found' = 4, 'already_exists' = 5, 'permission_denied' = 6, 'resource_exhausted' = 7, 'failed_precondition' = 8, 'aborted' = 9, 'out_of_range' = 10, 'unimplemented' = 11, 'internal' = 12, 'unavailable' = 13, 'data_loss' = 14, 'unauthenticated' = 15),
	`attr_rpc_jsonrpc_error_message`                     String,
	`attr_rpc_jsonrpc_request_id`                        String,
	`attr_rpc_jsonrpc_version`                           String,
	`attr_rpc_method`                                    String,
	`attr_rpc_service`                                   String,
	`attr_rpc_system`                                    String,
	`attr_server_address`                                String,
	`attr_session_id`                                    String,
	`attr_session_previous_id`                           String,
	`attr_source_address`                                String,
	`attr_state`                                         Enum8('idle' = 0, 'used' = 1),
	`attr_system_cpu_state`                              String,
	`attr_system_device`                                 String,
	`attr_system_filesystem_mode`                        String,
	`attr_system_filesystem_mountpoint`                  String,
	`attr_system_filesystem_state`                       Enum8('used' = 0, 'free' = 1, 'reserved' = 2),
	`attr_system_filesystem_type`                        String,
	`attr_system_memory_state`                           String,
	`attr_system_network_state`                          Enum8('close' = 0, 'close_wait' = 1, 'closing' = 2, 'delete' = 3, 'established' = 4, 'fin_wait_1' = 5, 'fin_wait_2' = 6, 'last_ack' = 7, 'listen' = 8, 'syn_recv' = 9, 'syn_sent' = 10, 'time_wait' = 11),
	`attr_system_paging_direction`                       Enum8('in' = 0, 'out' = 1),
	`attr_system_paging_state`                           Enum8('used' = 0, 'free' = 1),
	`attr_system_paging_type`                            Enum8('major' = 0, 'minor' = 1),
	`attr_system_processes_status`                       String,
	`attr_thread_name`                                   String,
	`attr_tls_cipher`                                    String,
	`attr_tls_client_certificate`                        String,
	`attr_tls_client_hash_md5`                           String,
	`attr_tls_client_hash_sha1`                          String,
	`attr_tls_client_hash_sha256`                        String,
	`attr_tls_client_issuer`                             String,
	`attr_tls_client_ja3`                                String,
	`attr_tls_client_not_after`                          String,
	`attr_tls_client_not_before`                         String,
	`attr_tls_client_server_name`                        String,
	`attr_tls_client_subject`                            String,
	`attr_tls_curve`                                     String,
	`attr_tls_next_protocol`                             String,
	`attr_tls_protocol_name`                             String,
	`attr_tls_protocol_version`                          String,
	`attr_tls_server_certificate`                        String,
	`attr_tls_server_hash_md5`                           String,
	`attr_tls_server_hash_sha1`                          String,
	`attr_tls_server_hash_sha256`                        String,
	`attr_tls_server_issuer`                             String,
	`attr_tls_server_ja3s`                               String,
	`attr_tls_server_not_after`                          String,
	`attr_tls_server_not_before`                         String,
	`attr_tls_server_subject`                            String,
	`attr_url_fragment`                                  String,
	`attr_url_full`                                      String,
	`attr_url_path`                                      String,
	`attr_url_query`                                     String,
	`attr_url_scheme`                                    String,
	`attr_user_agent_original`                           String,
	-- end
	-- resource attributes
	`resource`                                           LowCardinality(String),
	`res_faas_max_memory`                                Int64,
	`res_host_cpu_cache_l2_size`                         Int64,
	`res_host_cpu_stepping`                              Int64,
	`res_process_parent_pid`                             Int64,
	`res_process_pid`                                    Int64,
	`res_android_os_api_level`                           String,
	`res_android_state`                                  Enum8('created' = 0, 'background' = 1, 'foreground' = 2),
	`res_browser_language`                               String,
	`res_browser_platform`                               String,
	`res_cloud_account_id`                               String,
	`res_cloud_availability_zone`                        String,
	`res_cloud_platform`                                 String,
	`res_cloud_provider`                                 String,
	`res_cloud_region`                                   String,
	`res_cloud_resource_id`                              String,
	`res_container_command`                              String,
	`res_container_command_line`                         String,
	`res_container_id`                                   String,
	`res_container_image_id`                             String,
	`res_container_image_name`                           String,
	`res_container_name`                                 String,
	`res_container_runtime`                              String,
	`res_deployment_environment`                         String,
	`res_device_id`                                      String,
	`res_device_manufacturer`                            String,
	`res_device_model_identifier`                        String,
	`res_device_model_name`                              String,
	`res_faas_cron`                                      String,
	`res_faas_document_collection`                       String,
	`res_faas_document_name`                             String,
	`res_faas_document_operation`                        String,
	`res_faas_instance`                                  String,
	`res_faas_invocation_id`                             String,
	`res_faas_invoked_name`                              String,
	`res_faas_invoked_provider`                          String,
	`res_faas_invoked_region`                            String,
	`res_faas_name`                                      String,
	`res_faas_trigger`                                   Enum8('datasource' = 0, 'http' = 1, 'pubsub' = 2, 'timer' = 3, 'other' = 4),
	`res_faas_version`                                   String,
	`res_heroku_app_id`                                  String,
	`res_heroku_release_commit`                          String,
	`res_heroku_release_creation_timestamp`              String,
	`res_host_arch`                                      String,
	`res_host_cpu_family`                                String,
	`res_host_cpu_model_id`                              String,
	`res_host_cpu_model_name`                            String,
	`res_host_cpu_vendor_id`                             String,
	`res_host_id`                                        String,
	`res_host_image_id`                                  String,
	`res_host_image_name`                                String,
	`res_host_image_version`                             String,
	`res_host_name`                                      String,
	`res_host_type`                                      String,
	`res_os_build_id`                                    String,
	`res_os_description`                                 String,
	`res_os_name`                                        String,
	`res_os_type`                                        String,
	`res_os_version`                                     String,
	`res_process_command`                                String,
	`res_process_command_line`                           String,
	`res_process_executable_name`                        String,
	`res_process_executable_path`                        String,
	`res_process_owner`                                  String,
	`res_process_runtime_description`                    String,
	`res_process_runtime_name`                           String,
	`res_process_runtime_version`                        String,
	`res_service_instance_id`                            String,
	`res_service_name`                                   String,
	`res_service_namespace`                              String,
	`res_service_version`                                String,
	`res_telemetry_distro_name`                          String,
	`res_telemetry_distro_version`                       String,
	`res_telemetry_sdk_language`                         String,
	`res_telemetry_sdk_name`                             String,
	`res_telemetry_sdk_version`                          String,
	`res_webengine_description`                          String,
	`res_webengine_name`                                 String,
	`res_webengine_version`                              String,
	-- end
	-- scope attributes
	`scope`                                              LowCardinality(String),
	-- end
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (`name_normalized`, `resource`, `attribute`, `timestamp`)
