name: Commit linter

on:
  pull_request:
  workflow_dispatch:

# Common Go workflows from go faster
# See https://github.com/go-faster/x
jobs:
  check:
    uses: go-faster/x/.github/workflows/commit.yml@main
