name: 'Complience'

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  promql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: start
        run: docker compose -f dev/local/ch-compliance/docker-compose.yml up -d
      - name: stop
        run: docker compose -f dev/local/ch-compliance/docker-compose.yml down -v